spring:
  datasource:
    url: jdbc:mysql://fastforward-mysql:3306/fastforward
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
      active:
        - console-log
        - file-log
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  config: classpath:logback.xml
  level:
    org.hibernate.SQL: debug

external:
  api:
    url: https://query1.finance.yahoo.com
    default:
      - symbol: "005930.KS"
      - interval: "1d"
      - range: "5d"
